Update azfilesauth-build.yaml for Azure Pipelines

diff --git a/.github/azfilesauth-build.yaml b/.github/azfilesauth-build.yaml
--- a/.github/azfilesauth-build.yaml
+++ b/.github/azfilesauth-build.yaml
@@ -8,14 +8,44 @@ variables:
 - name: checkoutBranch
   value: release7
 
-stages: 
+stages:
+  - stage: TestCommands
+    displayName: 'Testing Commands (Not required stage)'
+    jobs:
+    - job: Test
+      displayName: 'Testing'
+      pool:
+        vmImage: 'ubuntu-latest'
+
+      steps:
+        - script: |
+            set -x
+            test_fun() {
+              echo "Running from test function"
+            }
+            test_fun
+          displayName: 'Build DEB Package'
+
   - stage: BuildPackages
     displayName: 'Build and Package DEB/RPM Artifacts'
     jobs:
     - job: BuildDEB
       displayName: 'Build DEB'
+      strategy:
+        matrix:
+          ubuntu20:
+            containerImage: ubuntu:20.04
+            releaseName: 'focal'
+          ubuntu22:
+            containerImage: ubuntu:22.04 
+            releaseName: 'jammy'
+          ubuntu24:
+            containerImage: ubuntu:24.04
+            releaseName: 'noble'
+      
+      container: $(containerImage)
       pool:
-        vmImage: 'ubuntu-22.04'
+        vmImage: 'ubuntu-latest'
 
       steps:
         - checkout: self
@@ -24,27 +54,19 @@ stages:
 
         - script: |
             set -x
-            git branch
-            git checkout $(checkoutBranch)
-            git --no-pager log -n 5
-            echo "Building DEB package..."
             chmod +x package-deb.sh
-            ./package-deb.sh
+            ./package-deb.sh $(releaseName)
           displayName: 'Build DEB Package'
 
         - script: |
             set -x
-            pwd
-            echo "Copying DEB package to artifacts..."
-            mkdir -p $(Build.ArtifactStagingDirectory)
-            cp PACKAGES/deb/*.deb $(Build.ArtifactStagingDirectory)
-            echo "Listing Built Files..."
-            ls -R $(Build.ArtifactStagingDirectory)
-          displayName: 'Copy DEB Package to Artifacts'
+            mkdir -p $(Build.ArtifactStagingDirectory)/$[ matrix.releaseName ]
+            cp PACKAGES/deb/*.deb $(Build.ArtifactStagingDirectory)/$[ matrix.releaseName ]
+          displayName: 'Stage DEB Package'
 
         - task: PublishBuildArtifacts@1
           inputs:
-            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
+            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$[ matrix.releaseName ]'
             ArtifactName: 'azfilesauth-deb'
 
 
@@ -261,7 +283,7 @@ stages:
               downloadPath: $(Build.ArtifactStagingDirectory)
 
           - task: AzureCLI@2
-            displayName: 'Test PMC installation'
+            displayName: 'Publish Packages'
             inputs:
               addSpnToEnvironment: true
               azureSubscription: 'AzFilesAuthenticator-wif'
@@ -281,41 +303,69 @@ stages:
                 # PMC="echo pmc --auth-type wif --base-url $PMC_BASE_URL"
                 PMC="pmc --auth-type wif --base-url $PMC_BASE_URL"
 
-                echo "Looking for .deb files..."
-                for PKG_FILE in *.deb; do
-                  [ -e "$PKG_FILE" ] || { echo "No .deb files found. Skipping APT upload."; break; }
+                publish_package() {
+                  local pkg_file="$1"
+                  local repo_name="$2"
+                  local release_name="${3:-}"
 
-                  echo "Uploading $PKG_FILE to PMC..."
-                  PKG_ID=$($PMC --id-only package upload "$PKG_FILE") || {
-                    echo "Failed to upload $PKG_FILE"
+                  echo "Uploading $pkg_file to PMC..."
+                  PKG_ID=$($PMC --id-only package upload "$pkg_file") || {
+                    echo "Failed to upload $pkg_file"
                     exit 1
                   }
 
-                  echo "Adding package $PKG_ID to repo microsoft-ubuntu-jammy-prod-apt"
-                  $PMC repo package update --add-packages "$PKG_ID" microsoft-ubuntu-jammy-prod-apt jammy
+                  if [ -n "$release_name" ]; then
+                    echo "Adding package $PKG_ID to repo $repo_name (release=$release_name)"
+                    $PMC repo package update --add-packages "$PKG_ID" "$repo_name" "$release_name"
+                  else
+                    echo "Adding package $PKG_ID to repo $repo_name"
+                    $PMC repo package update --add-packages "$PKG_ID" "$repo_name"
+                  fi
 
-                  echo "Publishing repo microsoft-ubuntu-jammy-prod-apt"
-                  $PMC repo publish microsoft-ubuntu-jammy-prod-apt
-                done
+                  echo "Publishing repo $repo_name"
+                  $PMC repo publish "$repo_name"
+                }
 
-                echo "Looking for azl3 RPM files..."
-                for PKG_FILE in *azl3*.rpm; do
-                  [ -e "$PKG_FILE" ] || { echo "No matching RPM files found. Skipping YUM upload."; break; }
+                publish_package *.focal.deb microsoft-ubuntu-focal-prod-apt focal
+                publish_package *.jammy.deb microsoft-ubuntu-jammy-prod-apt jammy
+                publish_package *.noble.deb microsoft-ubuntu-noble-prod-apt noble
+                publish_package *azl3*.rpm azurelinux-3.0-prod-ms-oss-x86_64-yum
 
-                  echo "Uploading $PKG_FILE to PMC..."
-                  PKG_ID=$($PMC --id-only package upload "$PKG_FILE") || {
-                    echo "Failed to upload $PKG_FILE"
-                    exit 1
-                  }
+                # echo "Looking for .deb files..."
+                # for PKG_FILE in *.deb; do
+                #   [ -e "$PKG_FILE" ] || { echo "No .deb files found. Skipping APT upload."; break; }
 
-                  echo "Adding package $PKG_ID to repo azurelinux-3.0-prod-ms-oss-x86_64-yum"
-                  $PMC repo package update --add-packages "$PKG_ID" azurelinux-3.0-prod-ms-oss-x86_64-yum
+                #   echo "Uploading $PKG_FILE to PMC..."
+                #   PKG_ID=$($PMC --id-only package upload "$PKG_FILE") || {
+                #     echo "Failed to upload $PKG_FILE"
+                #     exit 1
+                #   }
 
-                  echo "Publishing repo azurelinux-3.0-prod-ms-oss-x86_64-yum"
-                  $PMC repo publish azurelinux-3.0-prod-ms-oss-x86_64-yum
-                done
+                #   echo "Adding package $PKG_ID to repo microsoft-ubuntu-jammy-prod-apt"
+                #   $PMC repo package update --add-packages "$PKG_ID" microsoft-ubuntu-jammy-prod-apt jammy
 
-                echo "Done publishing packages."
+                #   echo "Publishing repo microsoft-ubuntu-jammy-prod-apt"
+                #   $PMC repo publish microsoft-ubuntu-jammy-prod-apt
+                # done
+
+                # echo "Looking for azl3 RPM files..."
+                # for PKG_FILE in *azl3*.rpm; do
+                #   [ -e "$PKG_FILE" ] || { echo "No matching RPM files found. Skipping YUM upload."; break; }
+
+                #   echo "Uploading $PKG_FILE to PMC..."
+                #   PKG_ID=$($PMC --id-only package upload "$PKG_FILE") || {
+                #     echo "Failed to upload $PKG_FILE"
+                #     exit 1
+                #   }
+
+                #   echo "Adding package $PKG_ID to repo azurelinux-3.0-prod-ms-oss-x86_64-yum"
+                #   $PMC repo package update --add-packages "$PKG_ID" azurelinux-3.0-prod-ms-oss-x86_64-yum
+
+                #   echo "Publishing repo azurelinux-3.0-prod-ms-oss-x86_64-yum"
+                #   $PMC repo publish azurelinux-3.0-prod-ms-oss-x86_64-yum
+                # done
+
+                # echo "Done publishing packages."
 
 
 
